version=9.0.1
group=absolemjackdaw
java_version=21
releasetype=release
changelog=add missing InBedChatScreen overlay

# Common
minecraft_version=1.21.11
minecraft_version_range=[1.21.11, 1.22)
parchment_minecraft=1.21.10
parchment_version=2025.10.12
neo_form_version=1.21.11-20251209.172050

# NeoForge
neoforge_version=21.11.17-beta
neoforge_loader_version_range=[4,)

# Fabric
fabric_version=0.140.2+1.21.11
fabric_loader_version=0.18.4

# Implementation
cardinal=7.3.0

# Mod options
mod_name=Public GUI Announcement
mod_author=AbsolemJackdaw
mod_id=publicguiannouncement
license=MIT
credits=
description=Shows a simple representation of the screen players are currently looking at

#Publishing
modrinth_project=EhsqBhQf
cf_project=341727

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
